on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Kmer_search

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build ./nber_eda -t ${{ secrets.LOGIN_SERVER }}/nber_eda
          docker push ${{ secrets.LOGIN_SERVER }}/nber_eda

          
 